config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'

  mount ActionCable.server => '/cable'

  post :send_message, to: 'messages#create', as: :new_message

  get :signin, to: 'sessions#new', as: :new_user_session
  delete :signout, to: 'sessions#destroy', as: :destroy_user_session
  post :signin, to: 'sessions#create', as: :user_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :set_user

  private

  def set_user

    redirect_to new_user_session_path unless session[:current_user].present?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def create
    translated_message = MessageTranslaterService.run(language: language_code, message: params[:content])
    ActionCable.server.broadcast 'messages',
      chat: {
        message: translated_message,
        user: params[:user],
        language: params[:language]
      }
    head :ok
  end

  private

  def language_code
     params[:language].split(" ")[0].downcase
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :set_user, only: [:new, :create]

  def new
    @languages = ["Yoda", "Valley Girl", "Binary Code"]
  end

  def destroy
    ActionCable.server.broadcast 'messages',
      conection: {
        user: session[:current_user],
        disconected: true
      }

    session[:current_user] = nil
    session[:current_language] = nil

    redirect_to new_user_session_path
  end

  def create
    session[:current_user] = params[:user]
    session[:current_language] = params[:language]

    ActionCable.server.broadcast 'messages',
      conection: {
        user: params[:user],
        conected: true
      }

    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="container">
  <div class="pull-right">
    <p>Signed in as <b><%= session[:current_user] %></b>&nbsp;<%= link_to 'logout', destroy_user_session_path, method: :delete %>.</p>
  </div>
  <div id='messages'></div>

  <%= form_tag new_message_path, id: :form_message, method: :post, remote: true do %>
    <%= hidden_field_tag :user, session[:current_user] %>
    <%= hidden_field_tag :language, session[:current_language] %>
    <div class="row">
      <div class="col col-lg-12">
        <%= text_field_tag :content, nil, class: 'form-control', autofocus: true, required: true %>
        <%= submit_tag 'send', class: 'btn btn-primary pull-right' %>
      </div>
    </div>
  <% end %>
</div>

<script>
  $(document).ready(function(){
    $('#form_message').on('ajax:success', function(){
      this.reset();
    })
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IMA - Instant Messaging Application</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootswatch/3.3.7/yeti/bootstrap.min.css" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>